CREATE TABLE MENU 
(
  CMENU_CODIGO CHAR(3 BYTE) NOT NULL 
, VMENU_NOMBRE VARCHAR2(100 BYTE) NOT NULL 
, VDES_ABREVIATURA VARCHAR2(15 BYTE) NOT NULL 
, CONSTRAINT XPKMENU PRIMARY KEY 
  (
    CMENU_CODIGO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE MENU
ADD CONSTRAINT DES_ABREV_UNIQUE UNIQUE 
(
  VDES_ABREVIATURA 
)
ENABLE;

// PERFILES
CREATE TABLE PERFILES 
(
  CPERF_CODIGO CHAR(4 BYTE) NOT NULL 
, VPERF_NOMBRE VARCHAR2(50 BYTE) 
, CPERF_ESTADO CHAR(1 BYTE) 
, CONSTRAINT XPKPERFILES PRIMARY KEY 
  (
    CPERF_CODIGO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

// tabla USUARIO_PERFILES
CREATE TABLE USUARIO_PERFILES 
(
  DFECH_REGISTRO DATE 
, IUSUARIO_CODIGO NUMBER(*, 0) NOT NULL 
, CPERF_CODIGO CHAR(4 BYTE) NOT NULL 
, CONSTRAINT XPKUSUARIO_PERFILES PRIMARY KEY 
  (
    IUSUARIO_CODIGO 
  , CPERF_CODIGO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE USUARIO_PERFILES
ADD CONSTRAINT FK_USU_PER_PERFIL FOREIGN KEY
(
  CPERF_CODIGO 
)
REFERENCES PERFILES
(
  CPERF_CODIGO 
)
ENABLE;

ALTER TABLE USUARIO_PERFILES
ADD CONSTRAINT R_40 FOREIGN KEY
(
  IUSUARIO_CODIGO 
)
REFERENCES USUARIO
(
  IUSUARIO_CODIGO 
)
ENABLE;


//MENU_ITEM
CREATE TABLE MENUITEM 
(
  CMENU_CODIGO CHAR(3 BYTE) NOT NULL 
, IDMENUITEM_CODIGO CHAR(11 BYTE) NOT NULL 
, VMENUITEM_NOMBRE VARCHAR2(100 BYTE) NOT NULL 
, CMENU_CODIGO_PADRE CHAR(3 BYTE) 
, CMENUITEM_CODIGO_PADRE CHAR(11 BYTE) 
, VURL VARCHAR2(250 BYTE) DEFAULT NULL 
, CFLG_ACCION CHAR(1 BYTE) NOT NULL 
, DDTM_CREACION DATE DEFAULT NULL 
, DDTM_ACTUALIZACION DATE DEFAULT NULL 
, VMENUITEM_DESCRIPCION VARCHAR2(200 BYTE) 
, CONSTRAINT XPKMENUITEM PRIMARY KEY 
  (
    CMENU_CODIGO 
  , IDMENUITEM_CODIGO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE MENUITEM
ADD CONSTRAINT IDMENUITEM_UNIQUE UNIQUE 
(
  IDMENUITEM_CODIGO 
)
ENABLE;

ALTER TABLE MENUITEM
ADD CONSTRAINT FK_MENUITEM_MENU FOREIGN KEY
(
  CMENU_CODIGO 
)
REFERENCES MENU
(
  CMENU_CODIGO 
)
ENABLE;

ALTER TABLE MENUITEM
ADD CONSTRAINT FK_MENUITEM_MENUITEM FOREIGN KEY
(
  CMENU_CODIGO_PADRE 
, CMENUITEM_CODIGO_PADRE 
)
REFERENCES MENUITEM
(
  CMENU_CODIGO 
, IDMENUITEM_CODIGO 
)
ENABLE;

CREATE UNIQUE INDEX MENUITEM_NOMBRE_UNIQUE ON MENUITEM (IDMENUITEM_CODIGO ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE UNIQUE INDEX XPKSUBMENU ON MENUITEM (CMENU_CODIGO ASC, IDMENUITEM_CODIGO ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

//PERFILES_MENUITEM
CREATE TABLE PERFILES_MENUITEM 
(
  CPERF_CODIGO CHAR(4 BYTE) NOT NULL 
, CMENU_CODIGO CHAR(3 BYTE) NOT NULL 
, DFECHA_REGISTRO DATE 
, IDMENUITEM_CODIGO CHAR(11 BYTE) NOT NULL 
, CONSTRAINT PERFILES_MENUITEM_PK PRIMARY KEY 
  (
    CPERF_CODIGO 
  , CMENU_CODIGO 
  , IDMENUITEM_CODIGO 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE PERFILES_MENUITEM
ADD CONSTRAINT FK_PERMEN_MENUITEM FOREIGN KEY
(
  CMENU_CODIGO 
, IDMENUITEM_CODIGO 
)
REFERENCES MENUITEM
(
  CMENU_CODIGO 
, IDMENUITEM_CODIGO 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE PERFILES_MENUITEM
ADD CONSTRAINT FK_PERMEN_PERFILES FOREIGN KEY
(
  CPERF_CODIGO 
)
REFERENCES PERFILES
(
  CPERF_CODIGO 
)
ENABLE;


// FUNCION ACTUALIZA SEQUENCE
create or replace 
PROCEDURE setSequence (seqname IN VARCHAR2, newnumber IN INTEGER) as
curr_val INTEGER;
curr_inc INTEGER;
curr_min INTEGER;
BEGIN
SELECT INCREMENT_BY, MIN_VALUE into curr_inc, curr_min from user_sequences where sequence_name = upper(seqname);
EXECUTE IMMEDIATE 'ALTER SEQUENCE ' ||seqname||' MINVALUE ' || LEAST((newnumber - curr_inc - 1) , curr_min) ;
EXECUTE IMMEDIATE 'SELECT ' ||seqname ||'.nextval FROM dual' INTO curr_val;
IF (newnumber - curr_val - curr_inc) != 0 THEN
EXECUTE IMMEDIATE 'ALTER SEQUENCE ' ||seqname||' INCREMENT BY '||(newnumber - curr_val - curr_inc);
END IF;
EXECUTE IMMEDIATE 'SELECT ' ||seqname ||'.nextval FROM dual' INTO curr_val;
EXECUTE IMMEDIATE 'ALTER SEQUENCE ' ||seqname||' INCREMENT BY ' || curr_inc;
END setSequence;

// TRIGGER INSERTA FECHA TABLA MUCHO A MUCHOS
create or replace 
trigger TAI_USUARIO_PERFILES 
BEFORE INSERT ON USUARIO_PERFILES 
FOR EACH ROW 
BEGIN
  :new.DFECH_REGISTRO := SysDate;
--  UPDATE USUARIO_PERFILES SET DFECH_REGISTRO = SysDate
--  WHERE  :new.IUSUARIO_CODIGO =  IUSUARIO_CODIGO and :new.CPERF_CODIGO  = CPERF_CODIGO;
END;